### ISSUE TITLE
Is there an easy way to set the font in the tooltip?

### ISSUE THREAD

**Issue by algotechnology** [tiaanduplessis/wenk#33]
CSS not my best subject!  Thanks.  It seems to pick up the font from the container ... cheers

**Comment by ebulku** [comment]
You can add this in your styles.css 

```css
[data-wenk]:after {
    font-family: 'Rubik'; /* Set your font family */
}
```
