### ISSUE TITLE
Question: How do I word wrap long text?

### ISSUE THREAD

**Issue by ghost** [tiaanduplessis/wenk#8]
Hi,

This is a very cool implementation.  I've got some long tooltips but could not figure out how to wrap the longer lines of text.  Any suggestions would be greatly appreciated.

Thanks,

Karl

**Comment by jackmcpickle** [comment]
@kdawg1406 if you use one of the defined width tooltips the text will overflow onto the next line automagical. 

Or create your own width if the large is too small. 
Eg.

``` css
[data-wenk].wenk-length--xlarge:after, {
  white-space: normal;
  width: 500px;
}
```
